// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jnSHh16PjgcDOymvfRUfQNZt41U7VMk',
    appId: '1:273619012635:android:404c0b4e3786f0f1047cbe',
    messagingSenderId: '273619012635',
    projectId: 'agrismart-app-1930c',
    storageBucket: 'agrismart-app-1930c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2jnSHh16PjgcDOymvfRUfQNZt41U7VMk',
    appId: '1:273619012635:android:404c0b4e3786f0f1047cbe',
    messagingSenderId: '273619012635',
    projectId: 'agrismart-app-1930c',
    storageBucket: 'agrismart-app-1930c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jnSHh16PjgcDOymvfRUfQNZt41U7VMk',
    appId: '1:273619012635:android:404c0b4e3786f0f1047cbe',
    messagingSenderId: '273619012635',
    projectId: 'agrismart-app-1930c',
    storageBucket: 'agrismart-app-1930c.firebasestorage.app',
    iosBundleId: 'com.example.crop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2jnSHh16PjgcDOymvfRUfQNZt41U7VMk',
    appId: '1:273619012635:android:404c0b4e3786f0f1047cbe',
    messagingSenderId: '273619012635',
    projectId: 'agrismart-app-1930c',
    storageBucket: 'agrismart-app-1930c.firebasestorage.app',
    iosBundleId: 'com.example.crop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2jnSHh16PjgcDOymvfRUfQNZt41U7VMk',
    appId: '1:273619012635:android:404c0b4e3786f0f1047cbe',
    messagingSenderId: '273619012635',
    projectId: 'agrismart-app-1930c',
    storageBucket: 'agrismart-app-1930c.firebasestorage.app',
  );
}
