apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ultra-crop-recommender-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 50
      timeoutSeconds: 600
      containers:
      - name: ultra-crop-recommender-api
        image: gcr.io/PROJECT_ID/ultra-crop-recommender:latest
        ports:
        - name: http1
          containerPort: 5020
        env:
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "5020"
        - name: DEBUG
          value: "false"
        - name: ENVIRONMENT
          value: "production"
        - name: MODEL_PATH
          value: "/app/models"
        - name: CACHE_TTL
          value: "3600"
        - name: ULTRA_REQUEST_TIMEOUT
          value: "10.0"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: openweather-api-key
        - name: GOOGLE_EARTH_ENGINE_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: google-earth-engine-key
        - name: BHUVAN_API_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: bhuvan-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: secret-key
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5020
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5020
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
