apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: market-price-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - name: market-price-api
        image: gcr.io/PROJECT_ID/market-price-api:latest
        ports:
        - name: http1
          containerPort: 5004
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_APP
          value: "production_market_price_api.py"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5004"
        - name: DEBUG
          value: "false"
        - name: DATABASE_URL
          value: "production_market_price.db"
        - name: API_VERSION
          value: "1.0.0"
        - name: API_NAME
          value: "Market Price API"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
