apiVersion: apps/v1
kind: Deployment
metadata:
  name: ultra-crop-api
  namespace: ultra-crop
  labels:
    app: ultra-crop-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ultra-crop-api
  template:
    metadata:
      labels:
        app: ultra-crop-api
        version: v1
    spec:
      containers:
      - name: ultra-crop-api
        image: gcr.io/PROJECT_ID/ultra-crop-api:latest
        ports:
        - containerPort: 5020
          name: http
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: API_PORT
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: DEBUG
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: ENVIRONMENT
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: MODEL_PATH
        - name: CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: ultra-crop-config
              key: CACHE_TTL
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: openweather-api-key
        - name: SOIL_GRIDS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: soil-grids-api-key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ultra-crop-secrets
              key: secret-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5020
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5020
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: models-volume
        emptyDir: {}
      restartPolicy: Always
